nuagenetworks/monolithe

- monolithe/specifications/repositorymanager.py
Added check in get_all_specifications(...) to filter out all files not under the repository_path.
> Add repository_path filter to get_all_specifications 

- monolithe/generators/lang/java/templates/pom.xml.tpl
- monolithe/generators/lang/java/writers/apiversionwriter.py
Allow configuration of the vspk-java library version, which will end up in the generated pom.xml, via library.ini.
> vspk-java 4.0.6

- monolithe/generators/lang/vro/templates/o11nplugin-core/model.java.tpl
Changed vRO code generator to not generate a getId() for a model entity if the entity already has an attribute called 'id'
> vspk-vro 4.0.6 #2

- monolithe/generators/lang/vro/templates/pom.xml.tpl
Removed default value for the build.number property in order for the Maven process on the Bamboo build server to always use the value of the build.number property passed on the command line.
> Removed default value for the build.number in pom.xml

- monolithe/generators/lang/go/templates/model.go.tpl
Couple of fixes for the Go VSPK:
- No CreateEntity method on entities that do not support it (for instance: No CreateContainer on a subnet, a container can not be created in a subnet)
- Changing of the Ancestor interface for each entity: 
- it had a CreateEntities method, which never exists (all CreateEntity used the single form of the Entity name). As such, the Ancestor interface was useless
- Switched to two interfaces:
- EntitiesAncestor: only has the GET request method (get a list of Entity as a requirement - An ancestor is any Object that can get a list of an Entity.)
- EntitiesParent: has both the GET request method and the POST request (create an Entity as a requirement. - A parent is an ancestor that can also create an Entity)
- The idea behind this is mimicking life: an Ancestor …
> Vspk go generator fix and better defaults

- monolithe/generators/lang/go/templates/session.go.tpl
Tested this with the current go-bambou and the one from nuagenetworks/go-bambou#4 , both work fine, so this should be merged and used for VSPK 4.0.7
> Adding support for certificate based auth

- monolithe/generators/lang/java/writers/apiversionwriter.py
> Use Monolithe's --generation-version argument for generated vspk-java

- monolithe/generators/lang/javascript/templates/entity.js.tpl
- monolithe/generators/lang/javascript/writers/apiversionwriter.py
Generated generic enum class NUIPTypeEnum.js
````
import { Enum } from 'enumify';
class NUIPTypeEnum extends Enum {}
NUIPTypeEnum.initEnum(['IPv6Network', 'IPv4Network', 'DUALSTACK', 'IPv4', 'IPv6']);
export default NUIPTypeEnum;
````
Generated generic enum class NUEnabledEnum.js
````
import { Enum } from 'enumify';
class NUEnabledEnum extends Enum {}
NUEnabledEnum.initEnum(['DISABLED', 'ENABLED', 'INHERITED']);
export default NUEnabledEnum;
````
Generated entity class NUSubnet.js
````
import NUAbstractNamedEntity from './abstract/NUAbstractNamedEntity';
import { NUSubnetDefaultActionEnum, NUSubnetResourceTypeEnum, NUSubnetEntityStateEnum } from
'./enums';
import { …
```
> vspk js generator - handle list, integer, float, generic enum classes

- monolithe/generators/lang/javascript/templates/entity.js.tpl
@natabal noticed a userlabel in spec file using single quote within. hence changing the format to use back-ticks.
> back ticks for userlabels

- monolithe/generators/lang/javascript/templates/entity.js.tpl
- monolithe/generators/lang/javascript/writers/apiversionwriter.py
Sample generated model.js:
Entity without any job command
```
import NUAbstractNamedEntity from './abstract/NUAbstractNamedEntity';
import { NUZFBAutoAssignmentZFBMatchAttributeEnum } from './enums';
/* Represents ZFBAutoAssignment entity
ZFB Enterprise Auto Assignment
*/
export default class NUZFBAutoAssignment extends NUAbstractNamedEntity {
ZFBMatchAttribute: null,
ZFBMatchAttributeValues: null,
priority: null,
associatedEnterpriseID: null,
associatedEnterpriseName: null,
});
}
static entityDescriptor = {
description: `ZFB Enterprise Auto Assignment `,
userlabel: `Enterprise Auto Assignment`,
}
static …
```
> generate getAllowedJobCommands

- monolithe/generators/lang/javascript/templates/entity.js.tpl
- monolithe/generators/lang/javascript/writers/apiversionwriter.py
Sample generated code:
When alarm supported:
```
import NUAbstractNamedEntity from './abstract/NUAbstractNamedEntity';
import { NUWANServiceServiceTypeEnum, NUWANServiceConfigTypeEnum, NUWANServiceTunnelTypeEnum }
from './enums';
import { NUPermittedActionEnum } from '@/enums';
/* Represents WANService entity
Represents a WAN Service Object.
*/
export default class NUWANService extends NUAbstractNamedEntity {
WANServiceIdentifier: null,
IRBEnabled: null,
permittedAction: null,
servicePolicy: null,
serviceType: null,
vnId: null,
enterpriseName: null,
domainName: null,
configType: null,
orphan: null,
useUserMnemonic: …
```
> generate supportsAlarms

- monolithe/generators/lang/javascript/templates/entity.js.tpl
sample generated code:
```
import { NUCommandCommandEnum, NUCommandStatusEnum, NUCommandOverrideEnum } from './enums';
/* Represents Command entity
A Command represents an operation that needs to be executed on an entity (NSG, Gateway, ...)
which requires little processing by VSD, but may result in a long activity on the external
entity.  An example would be to trigger an action on VSD so that a Gateway download a new image.
VSDs handling of the request is limited to generating a message to be sent to the device on which
the download process is expected.  The device then acts on the request and proceeds with the
download...  That may be a …
```
> undefined as default if default value not specified and for read-only attrs

- monolithe/generators/lang/javascript/templates/entity.js.tpl
- monolithe/generators/lang/javascript/writers/apiversionwriter.py
static method generated only if entity supports permissions,
Sample generated code:
```
import NUAbstractNamedEntity from './abstract/NUAbstractNamedEntity';
import { NUL2DomainTemplateEntityStateEnum, NUL2DomainTemplatePolicyChangeStatusEnum } from
'./enums';
import { NUEnabledEnum, NUIPTypeEnum } from '@/enums';
import { NUJobCommandEnum } from './enums';
/* Represents L2DomainTemplate entity
An L2 Domain is a distributed logical switch that enables L2 communication. An L2 Domain template
is a model that can be instantiated as often as required, thereby creating real, functioning L2
Domains.
*/
export default class NUL2DomainTemplate extends NUAbstractNamedEntity { …
```
> change for supportsPermissions

- monolithe/generators/lang/javascript/config/config.json
This was a new attribute added to api-spec.
Code snippet from generated NUVNF.js:
Before:
```
lastUserAction: new NUAttribute({
localName: 'lastUserAction',
attributeType: NUAttribute.ATTR_TYPE_ENUM,
description: `Last action perform by user`,
isReadOnly: true,
canSearch: true,
choices: [NUPermittedActionEnum.DEPLOY, NUPermittedActionEnum.REDEPLOY,
NUPermittedActionEnum.RESTART, NUPermittedActionEnum.START,
NUPermittedActionEnum.STOP, NUPermittedActionEnum.UNDEPLOY],
userlabel: `Last User Action`,
}),
```
After:
```
lastUserAction: new NUAttribute({
localName: 'lastUserAction',
attributeType: NUAttribute.ATTR_TYPE_ENUM,
description: `Last action perform by user`,
isReadOnly: true,
canSearch: true,
choices: [NUVNFLastUserActionEnum.DEPLOY, NUVNFLastUserActionEnum.REDEPLOY, …
```
> vspk-javascript: override for vnf.lastUserAction

- monolithe/generators/lang/javascript/config/config.json
- monolithe/generators/lang/javascript/templates/entity.js.tpl
- monolithe/generators/lang/javascript/writers/apiversionwriter.py
For now some of the specs use 'entity' and 'object' as subtype for list data type. I have just logged such attributes.
Sample (see attribute vscs in generated code below):
````
import NUVRS from './NUVRS';
import NUVSC from './NUVSC';
/* Represents NSGatewayMonitor entity
This API can be used to gather read-only information about an NSG, including information on its
state, system metrics, alarm counts, location and version. It is a single view of the full data
available for an NSG.
*/
export default class NUNSGatewayMonitor extends NUEntity {
vrsinfo: undefined,
vscs: …
```
> handle type list with subtype as any other spec

- monolithe/generators/lang/javascript/templates/locale_enum.json.tpl
- monolithe/generators/lang/javascript/writers/apiversionwriter.py
Sample generated file content:
```
{
"NUGatewayPersonalityEnum": {
"DC7X50": "DC7X50",
"EVDF": "EVDF",
"EVDFB": "EVDFB",
"HARDWARE_VTEP": "HARDWARE_VTEP",
"NETCONF_7X50": "NETCONF_7X50",
"NETCONF_THIRDPARTY_HW_VTEP": "NETCONF_THIRDPARTY_HW_VTEP",
"NUAGE_210_WBX_32_Q": "NUAGE_210_WBX_32_Q",
"NUAGE_210_WBX_48_S": "NUAGE_210_WBX_48_S",
"OTHER": "OTHER",
"VDFG": "VDFG",
"VRSB": "VRSB",
"VRSG": "VRSG",
"VSA": "VSA",
"VSG": "VSG"
}
}
```
> vspk-javascript: generate locale file for every enum

- monolithe/generators/lang/javascript/writers/apiversionwriter.py
If 'name' is not required, or 'name' is not filterable, or 'description' is required, or 'description' is not filterable, then the model class will extent NUEntity and not AbstractNamedEntity
> vspk-javascript: modify namedentity check

- monolithe/generators/lang/javascript/templates/entity.js.tpl
- monolithe/generators/lang/javascript/writers/apiversionwriter.py
- will be included only in model classes that support deployment failures (similar to how supportsPermissions is added)
- Sample generated code:
```
/* Represents EgressProfile entity
An Egress Profile represents an aggregation of IP, MAC and egress QoS profiles that are applied
on a VPort instance.
*/
export default class NUEgressProfile extends NUEntity {
name: undefined,
description: undefined,
assocEntityType: undefined,
associatedIPFilterProfileID: undefined,
associatedIPFilterProfileName: undefined,
associatedIPv6FilterProfileID: undefined, …
```
> Changes to include supportsDeploymentFailures

- monolithe/generators/lang/vro/templates/o11nplugin-core/pluginfactory.java.tpl
Java code was so large that it did not compile.  This is because a lot of the code was duplicated.  Solution was to keep track of objects used to generate code and only generate the code once.  Only template "pluginfactory.java.tpl" was changed.
> Reduce amount of Java code by eliminating duplicate if-then statements

- monolithe/generators/lang/python/converter.py
on vspk 0.0:
enableDHCPv4 was translated as enable_dhc_pv4
enableDHCPv6 was translated as enable_dhc_pv6
> Issue with translation of the enableDHCPv4 and enableDHCPv6 on python

- monolithe/generators/lang/javascript/templates/entity.js.tpl
- Earlier code was considering attribute type object only if type was object AND subtype was specified
- Fix: Do not consider subtype. Attribute type will be object if type is specified as object in api-spec
> fix attribute type object

- monolithe/generators/lang/javascript/templates/entity.js.tpl
- NSG assign to pending ZFBRequest was failing. Root cause was form validation failure due to data type mismatch. zfbrequest.lastConnectedTime was of type `time` in api-spec, but generated code was treating it as string
- Now treating type of such attributes as `NUAttribute.ATTR_TYPE_TIMESTAMP`
- Impacted classes `NUEventLog, NUGroup, NUIKECertificate, NULicense, NUVCenterHypervisor,` and `NUZFBRequest`
Sample generated attribute code:
```
lastConnectedTime: new NUAttribute({
localName: 'lastConnectedTime',
attributeType: NUAttribute.ATTR_TYPE_TIMESTAMP,
description: `The time in which the last GET was made from the gateway.`,
canOrder: true,
canSearch: true,
userlabel: `Last Connected Time`,
}),
```
> handle dataType time

- monolithe/generators/lang/javascript/templates/entity.js.tpl
Include minLength, maxLength, minValue, maxValue in attribute if provided in api-specification.
Sample generated code NUCommand.js:
```
import { NUCommandCommandEnum, NUCommandStatusEnum, NUCommandOverrideEnum } from './enums';
/* Represents Command entity
A Command represents an operation that needs to be executed on an entity (NSG, Gateway, ...)
which requires little processing by VSD, but may result in a long activity on the external
entity.  An example would be to trigger an action on VSD so that a Gateway download a new image.
VSDs handling of the request is limited to generating a message to be sent to the device on which
the …
```
> vspk-javascript: Include minLength, maxLength, minValue, maxValue in attribute if provided

- monolithe/generators/lang/javascript/writers/apiversionwriter.py
- do not support permissions if it is a template entity
- The following 12 files are impacted
```
$ diff --brief -r codegen codegen-base
codegen/javascript/6/models/NUDomainTemplate.js
codegen/javascript/6/models/NUGatewayTemplate.js
codegen/javascript/6/models/NUL2DomainTemplate.js
codegen/javascript/6/models/NUNSGatewayTemplate.js
codegen/javascript/6/models/NUNSPortTemplate.js
codegen/javascript/6/models/NUOverlayMirrorDestinationTemplate.js
codegen/javascript/6/models/NUPolicyGroupTemplate.js
codegen/javascript/6/models/NUPortTemplate.js
codegen/javascript/6/models/NURedirectionTargetTemplate.js
codegen/javascript/6/models/NUSubnetTemplate.js
codegen/javascript/6/models/NUVLANTemplate.js
codegen/javascript/6/models/NUZoneTemplate.js
```
The below function will not be generated anymore …
> Disable supportsPermissions on template specifications

- monolithe/generators/lang/javascript/config/config.json
- This is to fix incorrect enum type generation for addressOverrideType attribute
**Before:**
```
addressOverrideType: new NUAttribute({
localName: 'addressOverrideType',
attributeType: NUAttribute.ATTR_TYPE_ENUM,
description: `AddressOverride Type - either IPv4 or IPv6 or MACRO_GROUP. Possible values are IPV4, IPV6 and MACRO_GROUP.`,
canOrder: true,
canSearch: true,
choices: [NUIPTypeEnum.IPV4, NUIPTypeEnum.IPV6, NUIPTypeEnum.MACRO_GROUP],
userlabel: `Address Override Type`,
}),
```
**After:**
```
addressOverrideType: new NUAttribute({
localName: 'addressOverrideType',
attributeType: NUAttribute.ATTR_TYPE_ENUM,
description: `AddressOverride Type - either IPv4 or IPv6 or MACRO_GROUP. Possible values are IPV4, IPV6 and MACRO_GROUP.`,
canOrder: true,
canSearch: true,
choices: …
```
> fix addressOverrideType enum generation

- monolithe/generators/lang/vro/templates/o11nplugin-core/model.java.tpl
- monolithe/generators/lang/vro/templates/o11nplugin-core/pom.xml.tpl
- monolithe/generators/lang/vro/templates/pom.xml.tpl
- Removed getOwner, getCreationDate and getLastUpdateDate because it's in the specs now
- Dumped plugin-base, the new one uses bambou 2.0.31
> Updating bambou to 2.0.31
