MANIFEST.in

Just an update of the MANIFEST.in file so the ```python setup.py install``` command properly installs the correct files needed

Fix for issue #3

---

monolithe/generators/lang/java/templates/pom.xml.tpl

Reformatted and added more information to generated Maven file

Java bambou fixes

---

monolithe/generators/lang/html/templates/index.html.tpl

@little-dude needed to implement a fix because jinja2 apparently has a strong scope on the variables, so you have to do some trickery to have it actually be able to change a variable from outside the loop, inside a loop.
This works and gives clean api docs.
Please merge and urgently regenerate the vsd-api-documentation. Thanks!

Fix for API docs

---

monolithe/generators/lang/java/writers/apiversionwriter.py
monolithe/generators/lang/vro/writers/apiversionwriter.py

Use Monolithe's --generation-version argument for generated vspk-vro

---

monolithe/generators/lang/javascript/__init__.py
monolithe/generators/lang/javascript/templates/entity.js.tpl
monolithe/generators/lang/javascript/writers/apiversionwriter.py

first cut of javascript code generator - generates the model classes based on specifications

js code generator

---

monolithe/generators/lang/javascript/writers/apiversionwriter.py

@natabal pls take a look. as discussed, added 'ENABLED_INHERITED'. will push this in and regenerate vspk

Updating EnabledEnum

---

config/config.json
monolithe/generators/lang/javascript/writers/apiversionwriter.py

monolithe.ini to include additional line,
`config = config`

js codegen - config.json with overrides

---

monolithe/generators/lang/csharp/templates/AssemblyInfo.cs.tpl
monolithe/generators/lang/csharp/templates/package.nuspec.tpl
monolithe/generators/lang/csharp/templates/vspk.csproj.tpl
monolithe/generators/lang/csharp/vanilla/packages.config
monolithe/generators/lang/csharp/vanilla/vspk/vspk/packages.config
monolithe/generators/lang/csharp/writers/apiversionwriter.py

Added nuget spec file
Added package.config to automatically fetch bambou from nuget
Changet project name
Set assembly version properly

Adding nuget packaging and resolving for deps

---

monolithe/generators/lang/javascript/writers/apiversionwriter.py

@natabal This change is to always generate locales; in my code I had earlier set the default option as not to generate locale files. Changing the default option.

generate locales always

---

monolithe/generators/lang/javascript/writers/apiversionwriter.py

change double-quote if any in description text to single-quote

format description text

---

monolithe/generators/lang/html/templates/object.html.tpl
monolithe/generators/lang/html/writers/apiversionwriter.py
setup.py

@little-dude, have a look if this makes sense

Adding support for members as a separate header

---

monolithe/generators/lang/javascript/templates/entity.js.tpl

If subType provided in spec, same will be added to generated in JS code

js codegen - subtype changes

---

monolithe/generators/lang/javascript/templates/entity.js.tpl

sample generated file NUVLANTemplate.js:
```
import { NUVLANTemplateAssociatedConnectionTypeEnum, NUVLANTemplateTypeEnum } from './enums';
/* Represents VLANTemplate entity
Represents VLAN Template under a Port Template object.
*/
export default class NUVLANTemplate extends NUEntity {
isTemplate: true,
value: null,
description: null,
isUplink: false,
associatedConnectionType: null,
associatedEgressQOSPolicyID: null,
associatedIngressQOSPolicyID: null,
associatedUplinkConnectionID: null,
associatedVSCProfileID: null,
ducVlan: null,
type: null,
});
}
static entityDescriptor = { …
```

generate isTemplate

---

monolithe/generators/lang/java/templates/pom.xml.tpl

Updated the bambou version to 2.0.9

Updated Bambou version

---

monolithe/generators/lang/java/templates/pom.xml.tpl

Updating the bambou dependendy to 2.0.10 for java bambou.

Updating Bambou Dependency

---

monolithe/generators/lang/python/templates/cli.py.tpl
monolithe/generators/lang/python/templates/cli_commands.py.tpl
setup.py
tests/base/sdk/python/tdldk/cli/cli.py
tests/base/sdk/python/tdldk/cli/commands.py

@rvichery, verify i'm not doing anything stupid :p

Python cli support pages and default fetch of all objects

---

monolithe/generators/lang/python/templates/cli__init__.py.tpl
setup.py
tests/base/sdk/python/tdldk/cli/__init__.py

Fixes nuagenetworks/vspk-python#27 and nuagenetworks/bambou#17

Vsd cli fix tls

---

monolithe/generators/lang/javascript/templates/locale_enum.json.tpl
monolithe/generators/lang/javascript/writers/apiversionwriter.py

This reverts commit 35c54b76c99a37be3696122a99a69c68e0d9c033.

Revert "generate locale file for every enum (#111)"

---

monolithe/generators/lang/javascript/templates/locale_enum.json.tpl
monolithe/generators/lang/javascript/writers/apiversionwriter.py

This reverts commit bb3232ca46dd4aa62662f4c08132178dca0adea8.

vspk-javascript: add back enum locales generation

---

monolithe/generators/lang/python/vanilla/requirements.txt
setup.py
tests/base/sdk/python/requirements.txt

Related to nuagenetworks/bambou#21 & nuagenetworks/vspkgenerator#36

python vspk change requirements

---

monolithe/generators/lang/java/templates/pom.xml.tpl

bambou 2.0.16 supports bulk operations

Bumping bambou

---

monolithe/generators/lang/go/templates/session.go.tpl
setup.py

Fix vspk go 9

---

monolithe/generators/lang/javascript/writers/apiversionwriter.py

This reverts commit 120139251bcb35060275120a07f18abd4a39f0c5.

Revert "disable supportsPermissions on template specifications (#156)"

---

monolithe/generators/lang/javascript/templates/entity.js.tpl

Sample generated files: https://github.com/nuagenetworks/vspk-javascript/pull/13/files

vspk-javascript: support isTransient in attribute descriptor

---

monolithe/generators/lang/csharp/templates/package.nuspec.tpl
monolithe/generators/lang/csharp/templates/vspk.csproj.tpl
monolithe/generators/lang/csharp/vanilla/vspk/vspk/packages.config
monolithe/generators/lang/csharp/writers/apiversionwriter.py

It'd be nice if you could squash this when merging. Thanks

Csharp fixes

---

monolithe/generators/lang/javascript/config/config.json

Similar to https://github.com/nuagenetworks/monolithe/pull/164, but on two additional specs

fix addressOverrideType enum generation - 2

---

monolithe/generators/lang/java/templates/pom.xml.tpl

had to fix a small issue in bambou 2.0.29. Bumping this again.

Bumping bambou to 2.0.30
